version: '3.8'
services:
  db:
    image: postgres-custom
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pg_partman_bgw,pgaudit
    ports:
      - "${POSTGRES_PORT}:5432"