version: '3.8'
services:
  go:
    image: go-api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL','curl --fail localhost:8080/healthz || exit 1']
      interval: 10s
      timeout: 30s
      retries: 5
    ports:
      - 8080:8080
  db:
    image: postgres-custom
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pg_partman_bgw,pgaudit
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5